apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    tier: backend
    component: api 
spec:
  replicas: 2
  selector: 
    matchLabels:
      tier: backend
      component: api 
  
  template:
    metadata:
      labels:
        tier: backend
        component: api 
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1a
      containers:
      - name: backend
        image: naveenrajoli/2025backend:{{ .Values.deployment.imageversion }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi" 
        envFrom:
        - configMapRef:
            name: backend-config